/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Record({
  'difficulty' : IDL.Text,
  'playerName' : IDL.Text,
  'timeSeconds' : IDL.Nat,
  'movesCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'getTopScores' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Record({
    'difficulty' : IDL.Text,
    'playerName' : IDL.Text,
    'timeSeconds' : IDL.Nat,
    'movesCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'getTopScores' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };